name: build-warnings

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-warnings:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    # Limit run time to 15 min to avoid wasting action minutes.
    timeout-minutes: 15
    container: 
      image: centos:7.9.2009
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get essential tools needed on docker
        run: |
         yum -y update && yum clean all
         yum -y install wget
         yum install -y zip unzip
         yum install -y sudo
         yum install -y gcc-c++
      - name: Get admb and put in path
        run: |
          wget https://github.com/admb-project/admb/releases/download/admb-12.3/admb-12.3-linux.zip
          sudo unzip admb-12.3-linux.zip -d /usr/local/bin
          sudo chmod 755 /usr/local/bin/admb-12.3/bin/admb
          echo "/usr/local/bin/admb-12.3/bin" >> $GITHUB_PATH
          
      # Runs a set of commands using the runners shell
      - name: Build stock synthesis with warnings
        run: |
          rm -rf SS330
          rm -rf ss_linux.tar
          mkdir SS330
          /bin/bash ./Make_SS_330_new.sh -b SS330 -w
          
