name: build-win

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-win"
  build-win:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get admb and put in path
        run: |
          Invoke-WebRequest -Uri https://github.com/admb-project/admb/releases/download/admb-12.2/admb-12.2-windows.zip -OutFile "D:\a\stock-synthesis\stock-synthesis\admb-12.2.zip"
          Expand-Archive -LiteralPath "D:\a\stock-synthesis\stock-synthesis\admb-12.2.zip" -DestinationPath "D:\a\stock-synthesis\stock-synthesis\"
          echo "D:\a\stock-synthesis\stock-synthesis\admb-12.2\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
      - name: Build stock synthesis
        run: |
          cd Compile
          ./Make_SS_safe.bat
          ./Make_SS_fast.bat
          ./Make_SS_trans.bat

      - name: Move exes to a new folder
        run: |
          mkdir exes
          mv Compile/ss.exe exes/
          mv Compile/ss_opt.exe exes/
          mv Compile/ss_trans.exe exes/

      - name: Archive windows exes
        if: success()
        uses: actions/upload-artifact@main
        with:
          name: 'ss_win_exes'
          path: exes/
