name: build-mac

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-mac"
  build-mac:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install necessary tools
        run: |
          brew install zip
          brew install unzip

      # Runs a set of commands using the runners shell
      - name: Get admb and put in path
        run: |
          curl https://github.com/admb-project/admb/releases/download/admb-12.2/admb-12.2-macos-xcode12.zip -L -o admb-12.2.zip
          unzip admb-12.2.zip -d /usr/local/bin
          ls /usr/local/bin
          echo "/usr/local/bin/admb-12.2/bin" >> $GITHUB_PATH
          
      # Runs a set of commands using the runners shell
      - name: Build stock synthesis
        run: |
          rm -rf SS330
          mkdir SS330
          /bin/bash ./Make_SS_330_new.sh -b SS330
          cp SS330/ss . && shasum -a 256 ss
          
      # archive artifact
      - name: Upload check results
        if: success()
        uses: actions/upload-artifact@main
        with:
          name: ss
          path: ss
