on:
  workflow_dispatch:
  push:
    paths:
      - '**.tpl'
    branches: [main]
  pull_request:
    paths:
      - '**.tpl'
    branches: [main]
name: call-run-ss3-mcmc
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/run-ss3-mcmc.yml@main