# Build SS3 and run models without estimation and no hessian
name: call-run-ss3-no-est
on: 
  push:
    paths:
    - '**.tpl'
  workflow_dispatch:

jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/run-ss3-no-est.yml@main