on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: call-build-ss3-centos
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/build-ss3-centos.yml@main