# run fast running SS models with estimation
name: run-with-est
on: [workflow_dispatch]

jobs:
  run-with-est:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"

    steps:

      - name: Checkout ss repo
        uses: actions/checkout@v2
          
      - name: Checkout models repo
        uses: actions/checkout@v2
        with:
          repository: 'nmfs-stock-synthesis/ss-test-models'
          path: ss-test-models-repo
          
      - name: setup R  
        uses: r-lib/actions/setup-r@master
      
      - name: Get admb and put in path
        run: |
          wget https://github.com/admb-project/admb/releases/download/admb-12.3/admb-12.3-linux.zip
          sudo unzip admb-12.3-linux.zip -d /usr/local/bin
          sudo chmod 755 /usr/local/bin/admb-12.3/bin/admb
          echo "/usr/local/bin/admb-12.3/bin" >> $GITHUB_PATH
          
      - name: Build stock synthesis
        run: |
          rm -rf SS330
          mkdir SS330
          /bin/bash ./Make_SS_330_new.sh -b SS330

      - name: move exes, scripts to needed locations
        run: |
          mv ss-test-models-repo/models ss-test-models-repo/model_runs
          mv SS330/ss ss-test-models-repo/model_runs/ss
          mv ss-test-models-repo/jenkins/model/run_models.sh ss-test-models-repo/run_models.sh
          mv ss-test-models-repo/jenkins/compare/rename_ref_files.sh ss-test-models-repo/rename_ref_files.sh
          mv ss-test-models-repo/jenkins/compare/run_compare.R ss-test-models-repo/run_compare.R
      
      - name: keep only fast running models
        run: |
          keep_mods <- c("growth_timevary", "Hake_2018", "Hake_2019_semi-parametric_selex", 
            "Empirical_Wtatage_Age_Selex", "Simple_NoCPUE", "Simple", "Simple_with_Discard",
            "tagging_mirrored_sel", "three_area_nomove", "vermillion_snapper", "three_area",
            "growth_morphs", "KelpGreenling2015", BigSkate_2019")
          all_mods <- list.dirs(file.path("ss-test-models-repo", "model_runs"), full_names = FALSE, recursive = FALSE)
          rm_mods <- all_mods[!all_mods %in% keep_mods]
          # remove files for models that are not in 
          for (i in rm_mods) {
            tmp_rm_files <- list.files(file.path("ss-test-models-repo", "model_runs", i), full_names = TRUE)
            file.remove(tmp_rm_files) #rm files
            file.remove(file.path("ss-test-models-repo", "model_runs", i)) #rm dir
          }
        shell: Rscript {0}
          
      - name: change permissions on ss exes
        run: chmod a+x ss-test-models-repo/model_runs/ss
      
      - name: run models
        run: |
         cd ss-test-models-repo && run_models.sh
        
      - name: Run comparison
        run: |
          mkdir ss-test-models-repo/run_R
          cd ss-test-models-repo && Rscript run_compare.R
          
      - name: Determine results of test
        run: cd ss-test-models-repo && Rscript jenkins/shared/check_failed.R
      
      - name: Archive results
        uses: actions/upload-artifact@main
        if: always()
        with:
          name: 'result_textfiles'
          path: ss-test-models-repo/run_R/
          
